export const SET_DIOGRAPH = 'SET_DIOGRAPH'

export const ADD_DIORY = 'ADD_DIORY'
export const UPDATE_DIORY = 'UPDATE_DIORY'
export const REMOVE_DIORY = 'REMOVE_DIORY'

export const UPDATE_ROOM_BEGIN = 'UPDATE_ROOM_BEGIN'
export const UPDATE_ROOM_SUCCESS = 'UPDATE_ROOM_SUCCESS'
export const UPDATE_ROOM_FAILURE = 'UPDATE_ROOM_FAILURE'
