export const SET_DIOGRAPH = 'SET_DIOGRAPH'

export const ADD_DIORY = 'ADD_DIORY'
export const UPDATE_DIORY = 'UPDATE_DIORY'
export const REMOVE_DIORY = 'REMOVE_DIORY'

export const SAVE_ROOM_BEGIN = 'SAVE_ROOM_BEGIN'
export const SAVE_ROOM_SUCCESS = 'SAVE_ROOM_SUCCESS'
export const SAVE_ROOM_FAILURE = 'SAVE_ROOM_FAILURE'
