image:
  - macos-mojave
  - Visual Studio 2019
environment:
  CI: false
  TESTCAFE_TEST_ENV: "process.env.PWD=process.env.APPVEYOR_BUILD_FOLDER"
install:
  - npm install -g yarn
  - yarn global add testcafe electron
  - yarn && yarn build
before_build:
  - mkdir tmp
build_script:
  - bash ./run-e2e-tests.sh
