image:
  - macos-bigsur
  - Visual Studio 2022
environment:
  CI: false
  nodejs_version: '16'
install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm install -g yarn
  - yarn global add testcafe electron
  - yarn && yarn build
before_build:
  - mkdir tmp
build_script:
  - bash ./run-e2e-tests.sh
artifacts:
  - path: tmp/screenshots
    name: vr
    type: zip
