image:
  - macos-bigsur
  - Visual Studio 2019
environment:
  CI: false
install:
  - node --version
  - nvm install 16
  - nvm use 16
  - node --version
  - npm install -g yarn
  - yarn global add testcafe electron
  - yarn && yarn build
before_build:
  - mkdir tmp
build_script:
  - bash ./run-e2e-tests.sh
artifacts:
  - path: tmp/screenshots
    name: vr
    type: zip
