version: '3'

services:
  build:
    container_name: build
    build: .
    volumes:
      - .:/app
      - /app/node_modules
      - ~/.gitconfig:/etc/gitconfig
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    ports:
      - "${PORT:-3300}:3300"
