version: '3'

services:
  build:
    build: .
    volumes:
      - .:/app
      - node_modules:/node_modules
      - ~/.gitconfig:/etc/gitconfig
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    ports:
      - "${PORT:-3300}:3300"

volumes:
  node_modules: {}
