version: '3'

services:
  react:
    build: .
    container_name: react
    image: node:12.13
    working_dir: /app
    command: bash -c "yarn install && yarn start"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    ports:
      - "${PORT:-3300}:3300"
