module.exports = {
  channels: {
    GET_DIORY_HOME_ADDRESS: 'GET_DIORY_HOME_ADDRESS',
    SAVE_DIORY_HOME_ADDRESS: 'SAVE_DIORY_HOME_ADDRESS',
    OPEN_FOLDER: 'OPEN_FOLDER',
    OPEN_IN_BROWSER: 'OPEN_IN_BROWSER',
  },
}
