module.exports = {
  channels: {
    GET_DIORY_HOME_CONNECTION: 'GET_DIORY_HOME_CONNECTION',
    SAVE_DIORY_HOME_CONNECTION: 'SAVE_DIORY_HOME_CONNECTION',
    OPEN_FOLDER: 'OPEN_FOLDER',
    OPEN_IN_BROWSER: 'OPEN_IN_BROWSER',
  },
}
