module.exports = {
  channels: {
    GET_HOME_DIOGRAPH: 'GET_HOME_DIOGRAPH',
    SAVE_HOME_DIOGRAPH: 'SAVE_HOME_DIOGRAPH',
    OPEN_FOLDER: 'OPEN_FOLDER',
    OPEN_IN_BROWSER: 'OPEN_IN_BROWSER',
  },
}
