version: 0.2

phases:
  install:
    commands:
      - wget -qO - https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/Release.key | apt-key add -
      - apt-get update && apt-get install -y python3 python3-pip python3-setuptools groff less
      - pip3 install --upgrade pip
      - apt-get clean
      - pip3 --no-cache-dir install --upgrade awscli
  build:
    commands:
      - yarn && yarn build && yarn build-electron
      - echo "Add app-package-envs to electron-main.js"
      - export APP_PACKAGE_ENVS="process.env.BINARY_BUILD=1";
      - awk 'BEGIN{print ENVIRON["APP_PACKAGE_ENVS"]}{print}' build/electron-main.js > build/electron-main-tmp.js
      - mv build/electron-main-tmp.js build/electron-main.js
      - unset APP_PACKAGE_ENVS
      - yarn package-win
      - env
      - aws s3 cp "./dist/$WINDOWS_BINARY_FILENAME" s3://$WEBSITE_BUCKET --acl public-read
