export const GET_DIOGRAPH = 'GET_DIOGRAPH'
export const SAVE_DIOGRAPH = 'SAVE_DIOGRAPH'
export const ADD_DIOGRAPH = 'ADD_DIOGRAPH'

export const CREATE_DIORY = 'CREATE_DIORY'
export const UPDATE_DIORY = 'UPDATE_DIORY'
export const DELETE_DIORY = 'DELETE_DIORY'
