export const GET_DIOGRAPH = 'GET_DIOGRAPH'
export const GET_DIOGRAPH_BEGIN = 'GET_DIOGRAPH_BEGIN'
export const GET_DIOGRAPH_SUCCESS = 'GET_DIOGRAPH_SUCCESS'
export const GET_DIOGRAPH_FAILURE = 'GET_DIOGRAPH_FAILURE'

export const GET_STORY_BEGIN = 'GET_STORY_BEGIN'
export const GET_STORY_SUCCESS = 'GET_STORY_SUCCESS'
export const GET_STORY_FAILURE = 'GET_STORY_FAILURE'

export const GET_CONTEXT_BEGIN = 'GET_CONTEXT_BEGIN'
export const GET_CONTEXT_SUCCESS = 'GET_CONTEXT_SUCCESS'
export const GET_CONTEXT_FAILURE = 'GET_CONTEXT_FAILURE'

export const SAVE_DIOGRAPH = 'SAVE_DIOGRAPH'
export const SAVE_DIOGRAPH_BEGIN = 'SAVE_DIOGRAPH_BEGIN'
export const SAVE_DIOGRAPH_SUCCESS = 'SAVE_DIOGRAPH_SUCCESS'
export const SAVE_DIOGRAPH_FAILURE = 'SAVE_DIOGRAPH_FAILURE'

export const ADD_DIOGRAPH = 'ADD_DIOGRAPH'

export const CREATE_DIORY = 'CREATE_DIORY'
export const UPDATE_DIORY = 'UPDATE_DIORY'
export const DELETE_DIORY = 'DELETE_DIORY'
