export const ENTER_ROOM = 'ENTER_ROOM'
export const SET_FOCUS = 'SET_FOCUS'
export const GO_BACKWARD = 'GO_BACKWARD'
export const GO_FORWARD = 'GO_FORWARD'
export const GO_HOME = 'GO_HOME'
export const GO_LEFT = 'GO_LEFT'
export const GO_RIGHT = 'GO_RIGHT'
