# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cypress (cypress run)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SKIP_PREFLIGHT_CHECK: true
      CI: false
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.9.1
      - run: (cd diograph-js && yarn install && yarn build)
      - run: yarn install
      - run: yarn start & yarn run wait-on http://localhost:3300
      - run: yarn cypress run
